/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AddRouteImport } from './routes/add'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as EmisRouteImport } from './routes/emis'
import { Route as MoreRouteImport } from './routes/more'
import { Route as RecurringRouteImport } from './routes/recurring'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as AccountsAccountIdRouteImport } from './routes/accounts.$accountId'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const EmisRoute = EmisRouteImport.update({
  id: '/emis',
  path: '/emis',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurringRoute = RecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdRoute = AccountsAccountIdRouteImport.update({
  id: '/$accountId',
  path: '/$accountId',
  getParentRoute: () => AccountsRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/emis': typeof EmisRoute
  '/more': typeof MoreRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/transactions': typeof TransactionsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/emis': typeof EmisRoute
  '/more': typeof MoreRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/transactions': typeof TransactionsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/add': typeof AddRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cards': typeof CardsRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/emis': typeof EmisRoute
  '/more': typeof MoreRoute
  '/recurring': typeof RecurringRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/transactions': typeof TransactionsRoute
  '/accounts/$accountId': typeof AccountsAccountIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/add'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/categories'
    | '/emis'
    | '/more'
    | '/recurring'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/templates'
    | '/transactions'
    | '/accounts/$accountId'
    | '/cards/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/add'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/categories'
    | '/emis'
    | '/more'
    | '/recurring'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/templates'
    | '/transactions'
    | '/accounts/$accountId'
    | '/cards/$cardId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/add'
    | '/admin'
    | '/auth'
    | '/cards'
    | '/categories'
    | '/emis'
    | '/more'
    | '/recurring'
    | '/reports'
    | '/reset-password'
    | '/search'
    | '/settings'
    | '/templates'
    | '/transactions'
    | '/accounts/$accountId'
    | '/cards/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AddRoute: typeof AddRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CardsRoute: typeof CardsRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  EmisRoute: typeof EmisRoute
  MoreRoute: typeof MoreRoute
  RecurringRoute: typeof RecurringRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emis': {
      id: '/emis'
      path: '/emis'
      fullPath: '/emis'
      preLoaderRoute: typeof EmisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurring': {
      id: '/recurring'
      path: '/recurring'
      fullPath: '/recurring'
      preLoaderRoute: typeof RecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId': {
      id: '/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/accounts/$accountId'
      preLoaderRoute: typeof AccountsAccountIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof CardsRoute
    }
  }
}

interface AccountsRouteChildren {
  AccountsAccountIdRoute: typeof AccountsAccountIdRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsAccountIdRoute: AccountsAccountIdRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface CardsRouteChildren {
  CardsCardIdRoute: typeof CardsCardIdRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsCardIdRoute: CardsCardIdRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AddRoute: AddRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CardsRoute: CardsRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  EmisRoute: EmisRoute,
  MoreRoute: MoreRoute,
  RecurringRoute: RecurringRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
